### ISSUE TITLE
Bucket Boundaries error

### ISSUE THREAD

**Issue by hq23** [Kyubyong/dc_tts#19]
Hello,

I've got an issue when trying to run the training script with my input wav file.

The error is:
`ValueError: bucket_boundaries must not be empty`

I think it might be because of the length of the input files (1 minute).

Could anyone point me in the right direction on how to edit the hyperparams in order to be able to use a file of that length?

Is there any pointer/explanation besides the linked paper which explains the different parameters in hyperparams?

Thank you for your help.

**Comment by bprabhakar** [comment]
Facing the same issue, yes. Any workaround?

**Comment by hq23** [comment]
I've got it working by splitting up the source audio into multiple smaller files.

**Comment by dbarroso1** [comment]
what if my wav files are all under 10 seconds but i still get the error?

**Comment by PatrickAvis** [comment]
Did you get it working in the end? I've run into the same issue with clips that are under 5 seconds

**Comment by zshahid19** [comment]
Did u find any work around for files that are under 10 seconds?
