### ISSUE TITLE
how to test pretrained model on sound data?

### ISSUE THREAD

**Issue by m3m3-chan** [Kyubyong/dc_tts#44]
Hello, 
I am looking for realtime speech recognition. can I use the pretrained model to do that and How ?
I would appreciate it if anyone can give me tips on how to start with that.

Thanks,

**Comment by djebel-amila** [comment]
This repo is an implementation of a text-to-speech model, not speech-to-text. 
Have a look at these projects: [speech-to-text](https://github.com/topics/speech-to-text)

**Comment by m3m3-chan** [comment]
thanks for the reply. Will check the repo you suggested!
