### ISSUE TITLE
Cant synthesize audio

### ISSUE THREAD

**Issue by akashdeepjassal** [Kyubyong/dc_tts#45]
Traceback (most recent call last):
  File ".\synthesize.py", line 67, in <module>
    synthesize()
  File ".\synthesize.py", line 34, in synthesize
    saver1.restore(sess, tf.train.latest_checkpoint(hp.logdir + "-1"))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1264, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by PatrickAvis** [comment]
I get exactly the same issue - any luck getting it to work?

**Comment by akashdeepjassal** [comment]
I was able to rectify the issue. There should be a logdir directory with two sub-directories 
`Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       05-02-2018     10:06                LJ01-1
d-----       05-02-2018     10:06                LJ01-2
`

**Comment by PatrickAvis** [comment]
Thanks - a note for anyone else reading this...make sure you also update the hyperparamters.py to point to the samples directory

**Comment by fathimad11** [comment]
Heyy How You solve this i got same error

**Comment by ghost** [comment]
> I was able to rectify the issue. There should be a logdir directory with two sub-directories
> `Mode LastWriteTime Length Name
> 
> d----- 05-02-2018 10:06 LJ01-1
> d----- 05-02-2018 10:06 LJ01-2
> `

@akashdeepjassal can you please tell how many files are there in each directory, I am trying to convert it in tf v.2 and getting an unusual error
