### ISSUE TITLE
Can anyone help me describing how can I use this code for transfer learning to train with my own voice and fewer sample?

### ISSUE THREAD

**Issue by iampartho** [Kyubyong/dc_tts#50]

**Comment by PhilippMatthes** [comment]
You need to perform transfer learning, i.e. you have to train the existing pretrained model on your voice. Check out my fork to get started: https://github.com/PhilippMatthes/dc_tts/

**Comment by iampartho** [comment]
Thank you for your response but what I wanted to know is how can I load the
pretrain model in the training pipeline ? I will prepare data according to
LJ Speech dataset but I am not being able to load the pretrain model
weights to the network .
PS: I am new with tensorflow , I am really sorry if it's bother you :(

**Comment by PhilippMatthes** [comment]
The Model has to be downloaded first and it has to be put in the correct directory. See https://github.com/Kyubyong/dc_tts/issues/14 for more information on where to place the pretrained model. 
Once the model is in the correct directory, run `train.py 1` or `train.py 2` to train each of the models respectively. 10000 steps were sufficient on my use case. For the model to train, there must be a transcript like the one provided by the main dataset (see Readme) and audio samples, both correctly formatted/named and in the correct dir.
For further information on how to use the network look into the code itself, although the code is not designed nor documented well, it can be understood quickly. You do not need to understand the parts of `networks.py` to use the model. 
As I said, you can also check out my fork, where I already changed some parts of the code and added convenience wrappers to get it running on Python 3.5+.

**Comment by PhilippMatthes** [comment]
By the way, you don‘t need to download the whole dataset to obtain the transcript. AFAIK, I committed it to my fork as well.

**Comment by harirawat** [comment]
@iampartho I am also trying to generate voice by training with less data of my voice. 
Did you try this approach? Were you able to get good output?

**Comment by iampartho** [comment]
Thank you very much @PhilippMatthes for your suggestion. Sorry to get to it so late, I was busy with another project and use another repository (with great documentation) to solve this issue. But anyway I am really glad for your help.

@harirawat I am really sorry for this late reply but I want to inform you that I tried another approach which used pytorch framework and was able to generate TTS model with my voice , the result were not great but it's something, I guess. You can check that repository out if you wish https://github.com/r9y9/deepvoice3_pytorch

**Comment by fathimad11** [comment]
Hey I have a pretrained model of 734k step . How can I use that model in this code?
