### ISSUE TITLE
How to make tensorflow use gpu?

### ISSUE THREAD

**Issue by Traincraft101** [Kyubyong/dc_tts#58]
I don't know which version of tensorflow to use with the gpu. Does anyone have tensorflow-gpu working? I've been struggling to get this to work for days.

**Comment by mriganktiwari** [comment]
We tried training with tf 1.13, 1.14, 1.15 versions, but the code seems to use only CPU. Unable to make it use GPUs. Please help.

**Comment by tkgmomosheep** [comment]
Maybe try to uninstall the current version of tensorflow, then use `pip install tensorflow-gpu==1.14` to install the GPU version.

I am able to get it working under Python version 3.7.5 and Tensorflow 1.14.0.
Don't forget to install CUDA along the way.

**Comment by Traincraft101** [comment]
@tkgmomosheep Thanks!

**Comment by Traincraft101** [comment]
(I also have it working now on Python 3.6.0 with tensorflow 1.15.0 for anyone reading this)
