### ISSUE TITLE
ValueError: bucket_boundaries must not be empty

### ISSUE THREAD

**Issue by Subho95** [Kyubyong/dc_tts#80]
I am having the above error when running the "train" module. Any lead will be highly appreciable. Thanks in advance.

**Comment by ayunus22198** [comment]
Hey yes it is taking me a long time, like 12 hours plus just for train.py(I quit it in middle of code execution). Please let me know if you are able to get the code running within a day's time.

**Comment by Subho95** [comment]
> Hey yes it is taking me a long time, like 12 hours plus just for train.py(I quit it in middle of code execution). Please let me know if you are able to get the code running within a day's time.

My train.py is not even running. I am getting the above error while running the train.py module. Please let me know how this can be resolved.

**Comment by ayunus22198** [comment]
make sure you download LJ Speech and point the directory variable in hyperparams.py to that folder. Rename metadata to transcript, since training needs that

**Comment by Subho95** [comment]
I have done all the modifications to fir the model. But I think there is some problem while batching. I am getting the below error while running the train.py module.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-fb95463eb4dc> in <module>
    142     num = 1
    143 
--> 144     g = Graph(num=num); print("Training Graph loaded")
    145 
    146     logdir = hp.logdir + "-" + str(num)

<ipython-input-25-fb95463eb4dc> in __init__(self, num, mode)
     40         ## mags: Magnitude. (B, T, n_fft//2+1) float32
     41         if mode=="train":
---> 42             self.L, self.mels, self.mags, self.fnames, self.num_batch = get_batch()
     43             self.prev_max_attentions = tf.ones(shape=(hp.B,), dtype=tf.int32)
     44             self.gts = tf.convert_to_tensor(guided_attention())

<ipython-input-21-77f6d7ede048> in get_batch()
    129                                             num_threads=8,
    130                                             capacity=hp.B*4,
--> 131                                             dynamic_pad=True)
    132 
    133     return texts, mels, mags, fnames, num_batch

E:\Python Anaconda\lib\site-packages\tensorflow\contrib\training\python\training\bucket_ops.py in bucket_by_sequence_length(input_length, tensors, batch_size, bucket_boundaries, num_threads, capacity, bucket_capacities, shapes, dynamic_pad, allow_smaller_final_batch, keep_input, shared_name, name)
    372         bucket_boundaries)
    373   if not bucket_boundaries:
--> 374     raise ValueError("bucket_boundaries must not be empty")
    375   for (s, e) in zip(bucket_boundaries[:-1], bucket_boundaries[1:]):
    376     if not isinstance(s, int) or not isinstance(e, int):

ValueError: bucket_boundaries must not be empty

**Comment by Subho95** [comment]
This issue has been resolved. This error was due to my dataset in which maxlen+1 and minlen-1 were equal and hence the for loop was returning 0 elements in the list for the parameter bucket boundaries in bucket_by_sequence_length function.
