### ISSUE TITLE
text = [char2idx[char] for char in text] KeyError: ',' in data_load.py

### ISSUE THREAD

**Issue by SehejBakshi** [Kyubyong/dc_tts#83]
I am using python 3.7.9 with tf-gpu 2.1.0 in a conda environment on windows and I can't seem to run prepo.py due to the above issue.
First it was another issue at line 68 for which I had to delete the other 2 variables and just keep fname, _ and text. That worked out but I have been getting the KeyError since. No matter how many changes I make, it doesn't go.
`fname, _, text = line.strip().split("|")
                #duration = float(duration)
                #if duration > 10. : continue` (I modified the code to this since I was getting ValueError continuously)

I checked out the transcript.csv file (I am using LJSpeech1.1, encoded in UTF-8) and there are some wav files ending with a ',' which I think is the issue. But even if I add ',' in the vocabulary of the hyperparams.py file, it shows me another KeyError with another character. 

This is the whole error
`File "C:\Users\Public\Anaconda\Projects\DeepInfoLab\dc_tts-master\data_load.py", line 76, in <listcomp>
    text = [char2idx[char] for char in text]
KeyError: ','`

**Comment by vinamramunot-tech** [comment]
@SehejBakshi were you able to fix this?
