### ISSUE TITLE
ModuleNotFoundError: No module named 'pydub'

### ISSUE THREAD

**Issue by NoCodeAvaible** [Kyubyong/dc_tts#89]
Hello,

I get everytime I try to start commonvoice_create_jsons.py this error:

   from pydub import AudioSegment
ModuleNotFoundError: No module named 'pydub'

I don't know why it occurs because I've selected the right interpreter and I've downloaded the right version of pydub.
This error just freaks me out. 
Can someone please help me?

**Comment by saeidizadi** [comment]
you fixed it ?
I have this error
