### ISSUE TITLE
Rewriting Tensorflow 1.x code to tensorflow 2.x

### ISSUE THREAD

**Issue by neuronx1** [Kyubyong/dc_tts#95]
@Kyubyong 
Thanks for the great GitHub repository!
Unfortunatly my GPU only supports tensorflow 2.x and not 1.x .
For that reason I wanted to rewrite the Code to tensorflow 2.x .
Everything worked fine until line 122 in data_load.py
I haven't found a solution how to rewrite the following function: tf.contrib.training.bucket_by_sequence_length()
I am glad for any idea how to solve this problem.

**Comment by dmmagdal** [comment]
I've been working on that implementation in Tensorflow 2. I have my current progress public on my [Github](https://github.com/dmmagdal/dc_tts). At the moment, models have been trained for about 7-800K steps on the LJ Speech dataset but I'm yet to produce any discernable speech samples. If you think you can improve upon the existing code, I more than welcome the contribution. 

Only disclaimer is that I am in no way related to Kyubyong. I've never met the guy. I just like this repo and the project he's worked on with this.

**Comment by neuronx1** [comment]
@dmmagdal : Thank you very much!
